### ISSUE TITLE
Add .gitignore for stacks

### ISSUE THREAD

**Issue by a-roberts** [appsody/stacks#103]
**Is your feature request related to a problem? Please describe.**
I'm going to be developing locally before running and pushing my project, I figured I'd get a .gitignore so I don't need to add `node_modules` every time 😄 

**Describe the solution you'd like**
`.gitignore` with `node_modules` in

**Additional context**
Haven't tried other stacks, I'm using appsody CLI 0.2.5 (`appsody init nodejs-express`)

Probably want to ignore
```
	nodejs_dc.log
	nodejs_restclient.log
```

too

**Comment by neeraj-laad** [comment]
@a-roberts Thanks for raising this issue.

Yes, We would like to provide a .gitignore file for developers. Most of the stacks do that already, but might not be all in synch. 

In hte longer term, I'd like to get some of these common capabilities out from the template and move these to a shared place so that they are easy to maintain and keep them up to date. 

In the near-term we will review/ update the stacks to address these.

**Comment by tomleah** [comment]
These 2 log files have been committed to https://github.com/appsody/stacks/tree/master/incubator/nodejs-express/templates/simple. 

When this issue is resolved please remove these 2 files.

**Comment by tomleah** [comment]
Let's use https://github.com/github/gitignore/blob/master/Node.gitignore for Node.js stacks.

It might need some additions such as `.vscode`
