### ISSUE TITLE
Check if a newer version of CLI is available

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#158]
The CLI could check if there is a newer version and then suggest user to upgrade.

**Comment by kewegner** [comment]
We could do a GET on the URL URL below and check the output?

Since new releases are predicted in two week intervals, perhaps we want to do the check on the first invocation of appsody the current day? (perhaps tracking it by touching or updating a file in ~/HOME/.appsody directory.

 https://github.com/appsody/appsody/releases/latest 

Output:
<html><body>You are being <a href="https://github.com/appsody/appsody/releases/tag/0.3.0">redirected</a>.</body></html>
