### ISSUE TITLE
Appsody Liberty stacks should be based on UBI SFJ images 

### ISSUE THREAD

**Issue by irobins** [appsody/stacks#259]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behaviour**
What is the actual behaviour.

**Environment Details (please complete the following information):**

**If applicable please specify:**
 - CLI version:
 - Stack you are using:

**Screenshots**

**Additional context**

**Comment by neeraj-laad** [comment]
@gcharters @Emily-Jiang I would like to get your thoughts on this. 

Appsody would like to host stacks based on images that people are using today. This reduces the barrier for entry and helps with adoption.

Kabanero project consumes Appsody stacks and adds UBI images for their users.

**Comment by irobins** [comment]
@arthurdm any comments on this?

**Comment by arthurdm** [comment]
hi @irobins - I definitely agree with using UBI-min instead of Ubuntu, and back in July I had made a PR (https://github.com/appsody/stacks/pull/90) with this exact change.  

@neeraj-laad - is the issue main with IBM Small Footprint Java?     We are about to launch a new OL image which would have `UBI-min + AdoptOpenJDK + OL`, thus keeping everything open source.  Would that be a better fit?

UBI and UBI-min can be used by anyone, so in the cases we have those available I think we should use even in Appsody - it reduces the amount of changes a customer goes through when moving from Appsody into Kabanero.

**Comment by kilnerm** [comment]
Having the Appsody stack based on a ubi image would be helpful from the Kabanero collection perspective as it would allow us to use the base Docker files without the need to modify them.

Currently we build a stack on the ubi8 base because we didn't have an image available with stack elements matching the base, sounds like this new image will solve that problem.

**Comment by sympatheticmoose** [comment]
I'm not convinced we want ubi images as the default within Appsody. As @neeraj-laad has said, we are looking to use technologies as close to folks' current technology stack - which at this stage will be ubuntu not ubi. This is currently a major -1 from me.

**Comment by arthurdm** [comment]
hey guys, sorry for being away from the conversation for so long - this had dropped off my radar.

I think with the recent efforts to bring appsody stack and kabanero collections together we should revisit the decision to not use UBI images.

For Liberty, most customers will go into product using one of our new [UBI 8-based images](https://hub.docker.com/r/openliberty/open-liberty/), so it would be consistent with best practices to use the same image for both dev and prod scenarios.  

The UBI 8 standard image is viewed as more enterprise-ready and secured as compared to Ubuntu.    Customers can continue to use their RHEL satellites, and know that even their dev images would pass Red Hat certification.

Updating the Open Liberty stack would be as easy as changing [this line](https://github.com/appsody/stacks/blob/master/incubator/java-openliberty/image/project/Dockerfile#L29) to be:

 `FROM openliberty/open-liberty:kernel-java8-openj9-ubi`

**Comment by scottkurz** [comment]
@sympatheticmoose this isn't really a default, just an opinion for this particular stack.    Even if there's some value for consistency across stacks I'd guess an optimized experience for a single stack is more important.    Interesting to hear your response.

**Comment by neeraj-laad** [comment]
Appsody project should not dictate which base images the stacks should use. In fact, the starter appsody stack is based on UBI. So, Appsody will be happy to accept stacks based on ubuntu or ubi. 

It is more a question of what to stack maintainers feel is best for their developers.

**Comment by arthurdm** [comment]
Sounds good, thx @neeraj-laad     

@yeekangc / @scottkurz - I believe you guys are the current maintainers of the Open Liberty stack?

**Comment by scottkurz** [comment]
Assigned to @uberskigeek .... Can you please look at, from an appsody perspective, is there a "Go template" to easily switch the base image?    If so, then a Champ who wanted to build off Ubuntu e.g. would only need to modify this one property.   (If not it might be worth an issue against the appsody CLI since this would seem useful).  Thanks.

**Comment by scottkurz** [comment]
Planning on marking this resolved with the pending #650 PR.

A couple clarifications:
1. We are only making this change for the java-openliberty stack.   If we care to revisit this decision for any other stack, including java-microprofile, we can do that in a separate issue.
2. We are not going to use an SFJ image, but a more feature-rich UBI image, in fact the one suggested by arthurdm:
>  FROM openliberty/open-liberty:kernel-java8-openj9-ubi
