### ISSUE TITLE
Use maven cache for docker build

### ISSUE THREAD

**Issue by ebullient** [appsody/stacks#371]
**Is your feature request related to a problem? Please describe.**

Optimize building java applications in appsody by packing dependencies in the multi-stage build image. See https://github.com/halkyonio/operator/issues/149: 

> Observation: When a s2i or maven build will take place on the k8s platform, then the Maven Deps or GAVs needed to compile/package a java runtime as a uber jar will be downloaded for every build. This way of working is not really green/environmentally responsible and could be resolved by supporting a maven local cache

For our (appsody) purposes, this is specifically related to the artifacts used by the first stage of the multi-stage Dockerfile inside the stack image.

**Comment by kylegc** [comment]
Is this for building the stack image or the final production image with `appsody build`? 

My concern if this is for the `appsody build` image, is that we don't want artifacts from the development environment getting leaked into the production environment.
See slack discussion https://appsody.slack.com/archives/CKZ50HJET/p1568977956010600?thread_ts=1568969608.009400&cid=CKZ50HJET

**Comment by nastacio** [comment]
As I understand it, this would be for the first stage of the multi-stage build, used only during the creation of the war file that makes into the final stage.Denilson Nastacio==================dnastacio@gmail.com rtpscrolls.com
-------- Original message --------From: "Kyle G. Christianson" <notifications@github.com> Date: 9/20/19  5:01 PM  (GMT-05:00) To: appsody/stacks <stacks@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [appsody/stacks] Use maven cache for docker build (#371) Is this for building the stack image or the final production image with appsody build?
My concern if this is for the appsody build image, is that we don't want artifacts from the development environment getting leaked into the production environment.
See slack discussion https://appsody.slack.com/archives/CKZ50HJET/p1568977956010600?thread_ts=1568969608.009400&cid=CKZ50HJET

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/appsody/stacks/issues/371?email_source=notifications\u0026email_token=AAZAOH3OIQ5UPHIE5MK2YMLQKU2Z3A5CNFSM4IYYJUOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7H3XNQ#issuecomment-533707702",
"url": "https://github.com/appsody/stacks/issues/371?email_source=notifications\u0026email_token=AAZAOH3OIQ5UPHIE5MK2YMLQKU2Z3A5CNFSM4IYYJUOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7H3XNQ#issuecomment-533707702",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ebullient** [comment]
Right -- this isn't a way of pulling in dependencies from the developer's machine.. it's about avoiding redownloading the internet all of the other times. Pre-baking things into the stack a priori isn't all that good for Spring apps, and it means you're hauling a behemoth image all over the place. 

Travis, e.g., allows you to cache your dependencies (which would still be pulled from the required/configured repository): https://docs.travis-ci.com/user/caching/

In the linked item, the RH team are trying to sort out how to do the same thing, but around Tekton pipelines (and their buildah-based flow)

**Comment by awisniew90** [comment]
In PR #485 I layered the java-microprofile dockerfile so that maven dependencies are not re-downloaded each time the user's application source changes. This should speed up subsequent appsody builds. 

@ebullient - is this along the lines of what you were thinking, or am I misunderstanding the problem?
