### ISSUE TITLE
Update stacks CI scripts to use cli for packaging stacks

### ISSUE THREAD

**Issue by neeraj-laad** [appsody/stacks#422]
**Is your feature request related to a problem? Please describe.**
Today the logic for packaging a stack is included in shell scripts. We now have a cli command that can do this for us and we should look to update the CI scripts to use this command instead of doing the docker build and tar creation manually. This will also mean there is consistency between what stack creators have built/tested locally and what the CI will generate.

**Describe the solution you'd like**
update ci scripts to use appsody cli commands instead

**Comment by BarDweller** [comment]
#408 will need to be addressed first.

**Comment by groeges** [comment]
All stacks build except:
- incubator/java-microprofile (due to issues with latest stack)
- incubator/java-spring-boot2 (due to need for templating within the stack - issue open for this: https://github.com/appsody/stacks/issues/408 and PR: https://github.com/appsody/stacks/pull/509)
- experimental/java-spring-boot2-liberty (due to same issue as the incubator/java-spring-boot2)
- experimental/quarkus (seems to hang on `appsody build` step)
- experimental/rocket (due to need for templating within the stack)

**Comment by groeges** [comment]
New CI build issues are resolved with these PRs
- incubator/java-spring-boot2: https://github.com/appsody/stacks/pull/517
- experimental/java-spring-boot2-liberty: https://github.com/appsody/stacks/pull/509
- experimental/rocket: https://github.com/appsody/appsody/pull/634 (needs new CLI version)

incubator/java-microprofile and experimental/quarkus are still having issues building

**Comment by neeraj-laad** [comment]
All CI changes are merged. Issues have been raised for specific stacks that ned some changes.
