### ISSUE TITLE
Update the Open Liberty stack to use the Open Liberty Operator

### ISSUE THREAD

**Issue by arthurdm** [appsody/stacks#721]
**Is your feature request related to a problem? Please describe.**
Now that Appsody supports using other Operators to deploy the application stack, we should take advantage of specialized Operators when applicable for the best user experience.

**Describe the solution you'd like**
To use the Open Liberty Operator we simply need to update the Open Liberty Stack's `app-deploy.yaml` to have `Kind: OpenLibertyApplication` instead of `Kind: AppsodyApplication`. 

Things to check for:
* `appsody build` - ensuring the correct `app-deploy.yaml` gets generated with the same expected labels.
* `appsody deploy`  - knowing that the Appsody CLI will not check nor install the OL Operator, so that needs to be done prior.
*  Tekton deployment - deploy this updated stack using Kabanero.io's tekton pipeline to ensure it also gets deployed without issues.
* Update related documentation to point to the new Operator, specially highlighting the updates needed to `app-deploy.yaml` if they want to enable day2-operations (recommended for production)

**Comment by arthurdm** [comment]
fyi @scottkurz 

Someone in my team will do the PR, hopefully this week.

**Comment by arturdzm** [comment]
I've made the stack changes and have tested:

appsody build - ensuring the correct app-deploy.yaml gets generated with the same expected labels.
appsody deploy - knowing that the Appsody CLI will not check nor install the OL Operator, so that needs to be done prior.

I've ran into some issues installing Kabanero and Tekton, but that's due to my cluster most likely.
